---
filebeat_create_config: true

filebeat_prospectors:
  - input_type: log
    paths:
      - "/var/log/*.log"
    fields:
     logzio_codec: plain
     token: token
    files_under_root: true
    ignore_older: 3h   

filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "localhost:9200"

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "listener.logz.io:5015"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log

filebeat_ssl_dir: /etc/pki/tls/certs
filebeat_ssl_certificate_file: "etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt"
filebeat_ssl_key_file: ""
filebeat_ssl_insecure: "false"
